version: '3.8'

services:
  database:
    build:
      context: ./db
    container_name: app-db4
    ports:
      - "3315:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=TestPassword12!
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=TestPassword12!
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: app-backend4
    volumes:
      - ./frontend/templates:/app/templates  # Mount frontend/templates into backend
    ports:
      - "5005:5000"
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=testdb
    # depends_on:
    #   - database

    depends_on:
      database:
        condition: service_healthy  # Wait until MySQL is fully ready


  frontend:
    build:
      context: ./frontend
    container_name: app-frontend4
    ports:
      - "3004:3000"
    volumes:
      - ./frontend/templates:/app/templates
    depends_on:
      - backend

networks:
  default:
    name: app-network