---
- name: Deploy Web Application Locally
  hosts: localhost
  become: true  # Runs tasks with sudo

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present
        update_cache: yes

    - name: Clone the latest code from GitHub
      git:
        repo: "https://github.com/ayusao/test_lab.git"
        dest: "/home/{{ ansible_env.USER }}/test_lab"
        version: main
        force: yes

    - name: Ensure Docker images are up-to-date
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - Webapp/frontend
        - Webapp/backend

    - name: Stop existing containers (if any)
      docker_container:
        name: "{{ item }}"
        state: stopped
        remove: yes
      loop:
        - app-db2
        - app-backend2
        - app-frontend2

    - name: Run Docker Compose
      docker_compose:
        project_src: "/home/{{ ansible_env.USER }}/test_lab"
        restarted: yes
        removed: yes
