---
- name: Deploy Application on Localhost
  hosts: webserver
  tasks:

    - name: Ensure Docker is installed
      command: docker --version
      register: docker_version
      failed_when: docker_version.rc != 0
      changed_when: false

    - name: Pull latest code from GitHub
      git:
        repo: 'https://github.com/ayusao/test_lab.git'
        dest: /home/user/app
        version: main

    - name: Build and run Docker containers
      command: docker-compose up -d
      args:
        chdir: /home/user/app
