---
- name: Deploy Application on Localhost
  hosts: webserver
  tasks:

    - name: Ensure /home/ayusao/disk/labs/ansible directory exists
      file:
        path: /home/ayusao/disk/labs/ansible
        state: directory
        mode: '0777'

    - name: Pull latest code from GitHub
      git:
        repo: 'https://github.com/ayusao/test_lab.git'
        dest: /home/ayusao/disk/labs/ansible
        version: main

    - name: Build and run Docker containers
      command: docker-compose up -d
      args:
        chdir: /home/ayusao/disk/labs/ansible
